CREATE VIEW SUPPLY
  (CATERER.NAME, MATERIAL, MESSURE, SUPPLY_DATE, PRICE, VOLUME, SUMM)
AS
  SELECT CATERER.NAME, MATERIAL.NAME, MESSURE.NAME, 
         SUPPLY.SUPPLY_DATE, INPRICE.PRICE,
         SUPPLY.VOLUME, SUPPLY.VOLUME * INPRICE.PRICE
  FROM SUPPLY JOIN CATERER 
    ON SUPPLY.ID_CATERER = CATERER.ID_CATERER
  JOIN MATERIAL 
    ON SUPPLY.ID_MATERIAL = MATERIAL.ID_MATERIAL
  JOIN MESSURE 
    ON MATERIAL.ID_MESSURE = MESSURE.ID_MESSURE
  JOIN INPRICE 
    ON MATERIAL.ID_MATERIAL = INPRICE.ID_MATERIAL;