CREATE VIEW STORE
  (STORE, MATERIAL, MESSURE, SUMM)
AS
  SELECT STORE.NAME, MATERIAL.NAME, MESSURE.NAME,
         SUM(DELIVER.VOLUME)
    FROM DELIVER JOIN STORE 
      ON DELIVER.ID_STORE = STORE.ID_STORE    
    JOIN MATERIAL 
      ON DELIVER.ID_MATERIAL = MATERIAL.ID_MATERIAL
    JOIN MESSURE 
      ON MATERIAL.ID_MESSURE = MESSURE.ID_MESSURE
    WHERE DELIVER_DATE BETWEEN '01.01.2017' AND '31.12.2017'
  GROUP BY STORE.NAME, MATERIAL.NAME, MESSURE.NAME;